RedisExamples/AdventureWorksWeb/Models/DepartmentViewModel.cs
namespace AdventureWorksWeb.Models
{
    public class DepartmentViewModel
    {
        public string Name { get; set; }
        public string GroupName { get; set; }
    }
}

RedisExamples/AdventureWorksWeb/Models/ProductInventoryViewModel.cs
namespace AdventureWorksWeb.Models
{
    public sealed class ProductInventoryViewModel
    {
        public int Count { get; set; }
    }
}

RedisExamples/AdventureWorksWeb/Models/ProductReviewViewModel.cs
namespace AdventureWorksWeb.Models
{
    public sealed class ProductReviewViewModel
    {
        public string ReviewerName { get; set; }
        public int Rating { get; set; }
        public string Comments { get; set; }
        public int ProductId { get; set; }
    }
}

RedisExamples/AdventureWorksWeb/Models/PurchaseOrderHeaderViewModel.cs
using System;

namespace AdventureWorksWeb.Models
{
    public sealed class PurchaseOrderHeaderViewModel
    {
        public int PurchaseOrderId { get; set; }
        public int EmployeeId { get; set; }
        public int VendorId { get; set; }
        public int ShipMethodId { get; set; }
        public DateTime OrderDate { get; set; }
        public DateTime? ShipDate { get; set; }
        public decimal SubTotal { get; set; }
        public decimal TaxAmt { get; set; }
        public decimal Freight { get; set; }
        public decimal TotalDue { get; set; }
    }
}

RedisExamples/AdventureWorksWeb/Models/SalesPersonViewModel.cs
namespace AdventureWorksWeb.Models
{
    public sealed class SalesPersonViewModel
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public decimal SalesYtd { get; set; }
    }
}

RedisExamples/AdventureWorksWeb/Controllers/DepartmentsController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using AdventureWorksWeb.Models;
using AdventureWorksWeb.Repositories;
using AutoMapper;

namespace AdventureWorksWeb.Controllers
{
    public class DepartmentsController : Controller
    {
        private readonly IDepartmentRepository _departmentRepository;
        private readonly IMapper _mapper;

        public DepartmentsController(
            IDepartmentRepository departmentRepository,
            IMapper mapper)
        {
            _departmentRepository = departmentRepository;
            _mapper = mapper;
        }

        public async Task<ActionResult> Index()
        {
            var departments = await _departmentRepository.GetDepartmentsAsync();
            var departmentViewModels = _mapper.Map<IEnumerable<DepartmentViewModel>>(departments);
            return View(departmentViewModels);
        }
    }
}

RedisExamples/AdventureWorksWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdventureWorksWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

RedisExamples/AdventureWorksWeb/Controllers/InventoryController.cs
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using AdventureWorksWeb.Models;
using AdventureWorksWeb.Repositories;
using AutoMapper;

namespace AdventureWorksWeb.Controllers
{
    public class InventoryController : Controller
    {
        private readonly IProductInventoryRepository _productInventoryRepository;
        private readonly IMapper _mapper;

        public InventoryController(
            IProductInventoryRepository productInventoryRepository, 
            IMapper mapper)
        {
            _productInventoryRepository = productInventoryRepository;
            _mapper = mapper;
        }

        public async Task<ActionResult> Index()
        {
            var inventory = await _productInventoryRepository.GetProductInventoryAsync();
            var inventoryViewModel = new ProductInventoryViewModel {Count = inventory.Count()};
            return View(inventoryViewModel);
        }
    }
}

RedisExamples/AdventureWorksWeb/Controllers/ProductReviewsController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using AdventureWorksWeb.Models;
using AdventureWorksWeb.Repositories;
using AutoMapper;

namespace AdventureWorksWeb.Controllers
{
    public class ProductReviewsController : Controller
    {
        private readonly IProductReviewRepository _productReviewRepository;
        private readonly IMapper _mapper;

        public ProductReviewsController(
            IProductReviewRepository productReviewRepository,
            IMapper mapper)
        {
            _productReviewRepository = productReviewRepository;
            _mapper = mapper;
        }

        public async Task<ActionResult> Index()
        {
            var productReviews = await _productReviewRepository.GetProductReviewsAsync();
            var productReviewsViewModel = _mapper.Map<IEnumerable<ProductReviewViewModel>>(productReviews);
            return View(productReviewsViewModel);
        }
    }
}

RedisExamples/AdventureWorksWeb/Controllers/PurchaseOrderHeadersController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using AdventureWorksWeb.Models;
using AdventureWorksWeb.Repositories;
using AutoMapper;

namespace AdventureWorksWeb.Controllers
{
    public class PurchaseOrderHeadersController : Controller
    {
        private readonly IPurchaseOrderHeaderRepository _purchaseOrderHeaderRepository;
        private readonly IMapper _mapper;

        public PurchaseOrderHeadersController(
            IPurchaseOrderHeaderRepository purchaseOrderHeaderRepository,
            IMapper mapper)
        {
            _purchaseOrderHeaderRepository = purchaseOrderHeaderRepository;
            _mapper = mapper;
        }

        public async Task<ActionResult> PurchaseOrderHeadersString()
        {
            var purchaseOrderHeaders = await _purchaseOrderHeaderRepository.GetPurchaseOrderHeadersStringAsync();
            var purchaseOrderHeaderViewModels = _mapper.Map<IEnumerable<PurchaseOrderHeaderViewModel>>(purchaseOrderHeaders);
            return View(purchaseOrderHeaderViewModels);
        }

        public async Task<ActionResult> PurchaseOrderHeadersSet()
        {
            var purchaseOrderHeaders = await _purchaseOrderHeaderRepository.GetPurchaseOrderHeadersSetAsync();
            var purchaseOrderHeaderViewModels = _mapper.Map<IEnumerable<PurchaseOrderHeaderViewModel>>(purchaseOrderHeaders);
            return View(purchaseOrderHeaderViewModels);
        }


        public async Task<ActionResult> PurchaseOrderHeadersHashSet()
        {
            var purchaseOrderHeaders = await _purchaseOrderHeaderRepository.GetPurchaseOrderHeadersHashSetAsync();
            var purchaseOrderHeaderViewModels = _mapper.Map<IEnumerable<PurchaseOrderHeaderViewModel>>(purchaseOrderHeaders);
            return View(purchaseOrderHeaderViewModels);
        }
    }
}

RedisExamples/AdventureWorksWeb/Controllers/SalesController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using AdventureWorksWeb.Models;
using AdventureWorksWeb.Repositories;
using AutoMapper;

namespace AdventureWorksWeb.Controllers
{
    public class SalesController : Controller
    {
        private readonly ISalesPersonRepository _salesPersonRepository;
        private readonly IMapper _mapper;

        public SalesController(
            ISalesPersonRepository salesPersonRepository,
            IMapper mapper)
        {
            _salesPersonRepository = salesPersonRepository;
            _mapper = mapper;
        }

        public async Task<ActionResult> TopSalesPeople()
        {
            var salesPeople = await _salesPersonRepository.GetTopSalesPeopleAsync();
            var salesPeopleViewModel = _mapper.Map<IEnumerable<SalesPersonViewModel>>(salesPeople);
            return View(salesPeopleViewModel);
        }
    }
}

RedisExamples/AdventureWorksWeb/Views/Departments/Index.cshtml
@model System.Collections.Generic.IEnumerable<AdventureWorksWeb.Models.DepartmentViewModel>

@{
    ViewBag.Title = "AW Departments";
}

<h1 class="text-primary">AW Departments</h1>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Group</th>
    </tr>

    @foreach (var d in Model.OrderBy(d => d.Name))
    {
        <tr>
            <td>@d.Name</td>
            <td>@d.GroupName</td>
        </tr>
    }
</table>

RedisExamples/AdventureWorksWeb/Views/Inventory/Index.cshtml
@model AdventureWorksWeb.Models.ProductInventoryViewModel

@{
    ViewBag.Title = "Product Inventory Summary";
}

<h1 class="jumbotron">We have @($"{Model.Count:N0}") products!</h1>

RedisExamples/AdventureWorksWeb/Views/ProductReviews/Index.cshtml
@model System.Collections.Generic.IEnumerable<AdventureWorksWeb.Models.ProductReviewViewModel>

@{
    ViewBag.Title = "Product Reviews";
}

<h1 class="text-primary">Product Reviews</h1>
<table class="table">
    <tr>
        <th>Product Id</th>
        <th>Reviewed by</th>
        <th>Rating</th>
        <th>Review</th>
    </tr>

    @foreach (var r in Model)
    {
        <tr>
            <td>@r.ProductId</td>
            <td>@r.ReviewerName</td>
            <td>@r.Rating</td>
            <td>@r.Comments</td>
        </tr>
    }
</table>

RedisExamples/AdventureWorksWeb/Views/Sales/TopSalesPeople.cshtml
@model System.Collections.Generic.IEnumerable<AdventureWorksWeb.Models.SalesPersonViewModel>

@{
    ViewBag.Title = "Top Sales People";
}

<h1 class="text-primary">Top Sales People</h1>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Sales YTD</th>
    </tr>

    @foreach (var sp in Model)
    {
        <tr>
            <td>@sp.FirstName @sp.LastName</td>
            <td>@($"{sp.SalesYtd:c}")</td>
        </tr>
    }
</table>

RedisExamples/AdventureWorksWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Departments", "Index", "Departments")</li>
                    <li>@Html.ActionLink("Top Sales People", "TopSalesPeople", "Sales")</li>
                    <li>@Html.ActionLink("Reviews", "Index", "ProductReviews")</li>
                    <li>@Html.ActionLink("Inventory", "Index", "Inventory")</li>
                    <li>@Html.ActionLink("Purchases (string)", "PurchaseOrderHeadersString", "PurchaseOrderHeaders")</li>
                    <li>@Html.ActionLink("Purchases (set)", "PurchaseOrderHeadersSet", "PurchaseOrderHeaders")</li>
                    <li>@Html.ActionLink("Purchases (hash set)", "PurchaseOrderHeadersHashSet", "PurchaseOrderHeaders")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>